[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tracestorm"
version = "0.0.1"
description = "A replay tool for LLM requests"
authors = [
    {name="Yao Fu", email="yao.fu.aisys@gmail.com"}
]

dependencies = [
    "openai>=0.27.0",
]
